### ISSUE TITLE
在ViewPager中使用，图片放大后滑动直接切换到了下一个Item而不是滑出放大的图片不可见部分

### ISSUE THREAD

**Issue by ancode-cn** [ongakuer/PhotoDraweeView#1]

**Comment by ongakuer** [comment]
哦，还不支持ViewPager中使用

**Comment by ancode-cn** [comment]
请问有支持ViewPager的计划吗，我目前对事件分发掌握的不够深入，也学习下...

**Comment by ongakuer** [comment]
等有空重新改写一下。  不过主要移动和缩放都是基于[PhotoView](https://github.com/chrisbanes/PhotoView) , 你可以去看一下。

**Comment by ongakuer** [comment]
@ancode-cn 更新了一下，可以支持ViewPager滑动拦截了。

**Comment by ancode-cn** [comment]
感谢，但在缩放的时候部分情况下崩溃，报pointerindex out of range

**Comment by ongakuer** [comment]
有详细的崩溃信息吗？ 你用的安卓版本是什么？

**Comment by ancode-cn** [comment]
两三个手指同时缩放的时候会报异常
05-12 18:28:21.972: E/AndroidRuntime(19002): Process: com.zaozuo.app, PID: 19002
05-12 18:28:21.972: E/AndroidRuntime(19002): java.lang.IllegalArgumentException: pointerIndex out of range
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.MotionEvent.getX(MotionEvent.java:1983)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:110)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:462)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1841)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2059)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2314)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1692)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2739)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2275)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.View.dispatchPointerEvent(View.java:8578)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4028)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3894)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3456)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3509)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3475)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3585)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3483)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3642)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3456)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3509)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3475)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3483)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3456)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5708)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5682)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5653)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5798)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5769)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5821)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
05-12 18:28:21.972: E/AndroidRuntime(19002): 	at android.view.Choreographer.doC

**Comment by ancode-cn** [comment]
5.0版本，我觉得应该是多点触控处理的有问题，>=2 个手指缩放来回滑动就经常崩溃

**Comment by ongakuer** [comment]
额，我使用的就是5.0版。 你能跑一下 sample 试试会出现吗 ？

**Comment by ongakuer** [comment]
哦，我也能触发崩溃了，是在缩小到很小，自动放大的时候，多点触摸出现的吧？

**Comment by ancode-cn** [comment]
是的，2个及以上手指触摸缩放，然后来回切换item就会出问题

**Comment by ancode-cn** [comment]
用原有的PhotoView继承SimpleDraweeView也有这样的问题

**Comment by ongakuer** [comment]
恩，因为ViewPager支持多点触摸，但是图片多点缩放时会把 ViewPager 在  ACTION_DOWN ，ACTION_POINTER_DOWN 时的事件处理拦截了，导致ViewPager内部记录的 mActivePointerId 没有及时更新，导致  “pointerIndex out of range”

**Comment by ancode-cn** [comment]
有什么解决办法吗？

**Comment by ongakuer** [comment]
正在处理

**Comment by ongakuer** [comment]
大概要改动的地方可能会挺多的，有空我再慢慢调试了

**Comment by ancode-cn** [comment]
好的，很期待...

**Comment by ongakuer** [comment]
好了，思路错了。内部View要控制外层View的事件处理是不太好的。
https://code.google.com/p/android/issues/detail?id=60464

所以你重新改写一下ViewPager 就好了~

**Comment by ancode-cn** [comment]
好了，谢谢支持！
