### ISSUE TITLE
PhotoDraweeView 加载图片失败后，无法重新加载

### ISSUE THREAD

**Issue by e-hai** [ongakuer/PhotoDraweeView#11]
Fresco原来有个功能是加载图片失败后，显示加载失败的提示图片，点击后可以重新加载图片，但是PhotoDraweeView不可以了，怎么办

**Comment by ongakuer** [comment]
```
controller.setControllerListener(new BaseControllerListener<ImageInfo>() {
    @Override
    public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
        super.onFinalImageSet(id, imageInfo, animatable);
        if (imageInfo == null || mPhotoDraweeView == null) {
            return;
        }
        mPhotoDraweeView.update(imageInfo.getWidth(), imageInfo.getHeight());
    }
});
```

试试在imageInfo == null 的时候处理失败情况？

**Comment by e-hai** [comment]
![up zw pk n97mqinh 3g3](https://cloud.githubusercontent.com/assets/15882634/14730185/d667aa56-0876-11e6-90f0-32511d4dc89a.png)
失败了，点击后，完全没有反应，好像没有触发重新加载的事件。
下面的两个方法都没有被触发：
`ControllerListener controllerListener = new BaseControllerListener<ImageInfo>() {
        @Override
        public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
            super.onFinalImageSet(id, imageInfo, animatable);
            Log.d(TAG,"onFinalImageSet---");
            if (imageInfo == null||mPhotoView==null) {
                Log.d(TAG,"imageInfo == null");
                return;
            }
            Log.d(TAG,"成功");
            mPhotoView.update(imageInfo.getWidth(), imageInfo.getHeight());
        }

        @Override
        public void onFailure(String id, Throwable throwable) {
            super.onFailure(id, throwable);
            Log.d(TAG,"失败");
        }
    };`

**Comment by ongakuer** [comment]
点击触发重新加载你得在 ```setOnViewTapListener``` 自己处理一下这个逻辑。
至于加载失败在会回调到哪里，得查查Fresco文档

**Comment by e-hai** [comment]
嗯嗯，好的，非常感谢解答

**Comment by LeoYe168** [comment]
可以设置默认图片么

**Comment by ongakuer** [comment]
@LeoYe168   v1.1版本可以正常显示默认占位图和失败图了
