### ISSUE TITLE
加载中的进度条也被放大了，有解决方法吗

### ISSUE THREAD

**Issue by e-hai** [ongakuer/PhotoDraweeView#12]
我设置了进度条：
`GenericDraweeHierarchy hierarchy = new GenericDraweeHierarchyBuilder(mContext.getResources())
                .setActualImageScaleType(ScalingUtils.ScaleType.FIT_CENTER)
                .setProgressBarImage(new CustomProgressBar(mContext))
                .build();`
结果发现显示进度条过程中，也可以放大，有没有办法禁止加载过程中被放大呢！

**Comment by ongakuer** [comment]
哦，不好意思。 这个控件不支持设置ScaleType，只处理里居中放大模式…
