### ISSUE TITLE
Could not find any version that matches com.facebook.fresco:fresco:0.7.0+

### ISSUE THREAD

**Issue by ericbrandwein** [ongakuer/PhotoDraweeView#13]
I can't build this project, and gradle throws this error. Changing in the `gradle.build` the Fresco version to `0.7.0`, without the "`+`", fixes this. Here´s a [link](https://jitpack.io/com/github/ongakuer/PhotoDraweeView/-23230a2861-1/build.log) to the log.

**Comment by ongakuer** [comment]
Yes , you need upgrade Fresco to latest version.
