### ISSUE TITLE
Library on maven central

### ISSUE THREAD

**Issue by Bhullnatik** [ongakuer/PhotoDraweeView#14]
Hey!

Any reason this is not on Maven central? Importing and maintaining a library not in a central repository is a pain in the ass.
Since this library is linked from the README of [`PhotoView`](https://github.com/chrisbanes/PhotoView), I'm sure a lot of people would find this easier to use too. 🙂

Anyway thanks for the project!

**Comment by xsorifc28** [comment]
+1

Or, even on jitpack?

**Comment by ongakuer** [comment]
I think this is depend on Fresco. But Fresco update frequently. 
People who like to use this module can easily import it into project and choose Fresco version. 

Besides, this module is only support "CENTER" scale type.

**Comment by Bhullnatik** [comment]
@ongakuer I believe it's still possible to choose the Fresco version you want to use by specifying one higher than what the library currently uses. Besides maybe releasing it on a maven/jitpack will bring more people interested in the project that will work on updating Fresco regularly.

**Comment by milkrun** [comment]
Also want to do this -- How about forking it and then creating a library

**Comment by ongakuer** [comment]
Well, I will publish soon.

**Comment by ongakuer** [comment]
```
dependencies {
    compile 'com.facebook.fresco:fresco:0.10.0'
    compile 'me.relex:photodraweeview:1.0.0@aar'
}
```

**Comment by Bhullnatik** [comment]
Thanks a lot @ongakuer !
