### ISSUE TITLE
placeholderImage location error

### ISSUE THREAD

**Issue by sh1tge** [ongakuer/PhotoDraweeView#17]
i want to set placeholderImage when the image is loading,

`photoDraweeView.getHierarchy().setPlaceholderImage(getResources().getDrawable(R.drawable.default_img), ScalingUtils.ScaleType.CENTER);R.drawable.default_img`

but when i scroll the view  a few times  , the holderImage location is error;

like this:
![device-2016-06-15-171412](https://cloud.githubusercontent.com/assets/7855225/16074355/af5af4ec-331c-11e6-9499-0163014a8cde.png)
![device-2016-06-15-171431](https://cloud.githubusercontent.com/assets/7855225/16074357/b3432f5c-331c-11e6-9126-596520d44355.png)

**Comment by ongakuer** [comment]
```java
Drawable drawable = getResources().getDrawable(R.drawable.default_img);
photoDraweeView.getHierarchy().setPlaceholderImage(drawable);
photoDraweeView.update(drawable.getIntrinsicWidth(), drawable.getIntrinsicHeight());
```

**Comment by ongakuer** [comment]
Fixed https://github.com/ongakuer/PhotoDraweeView/commit/5ef9d966f7bf9d376e3b38d062acecd6664c825e
