### ISSUE TITLE
long images are muzzy when zoom

### ISSUE THREAD

**Issue by AllenVork** [ongakuer/PhotoDraweeView#21]
I have set the setDownsampleEnabled(true) option, but didn't set the resizeOption when I use the PhotoDraweeView to load images.But some images are still resized which leads to the images are muzzy when I zoom to enlarge them.

**Comment by ongakuer** [comment]
http://frescolib.org/docs/resizing-rotating.html

> If this option is on, the image pipeline will downsample your images instead of resizing them. You must still call setResizeOptions for each image request as above.
