### ISSUE TITLE
设置GenericDraweeHierarchy后，图片整个放大了

### ISSUE THREAD

**Issue by hcadoid** [ongakuer/PhotoDraweeView#24]
GenericDraweeHierarchy hierarchy=new GenericDraweeHierarchyBuilder(getResources())
                    .setProgressBarImage(R.drawable.default_ptr_rotate)
                    .build();
 photoDraweeView.setHierarchy(hierarchy);

**Comment by ongakuer** [comment]
不兼容 ProgressBarImage

**Comment by hcadoid** [comment]
GenericDraweeHierarchy的设置都不兼容吧，设置占位图，失败图，没有设置ScaleType属性也是放大的

**Comment by ongakuer** [comment]
对。 只实现了基本的 ScaleType FIT_CENTER 缩放。占位图 、失败图等 就都会应用 FIT_CENTER

**Comment by ongakuer** [comment]
更新了v1.1.0 ，占位图、失败图等 ScaleType可以使用了。
