### ISSUE TITLE
cannot  find a declaration to go to 

### ISSUE THREAD

**Issue by FrancisShi** [ongakuer/PhotoDraweeView#3]
I import the module but cant use it

**Comment by ongakuer** [comment]
有什么错误提示吗？

**Comment by FrancisShi** [comment]
没有 导入正常 但是无法引用到类

发自我的 iPhone

**Comment by ongakuer** [comment]
导入module后，你是不是忘了在app的中依赖module？

**Comment by FrancisShi** [comment]
居然忘记加
compile project(':photodraweeview')
整合到项目里啦，感谢分享，貌似fb也有个
[sample](https://github.com/facebook/fresco/tree/master/samples/zoomable/src/main/java/com/facebook/samples/zoomable)
以后应该会加入Fresco吧
