### ISSUE TITLE
关于加载进度条也可以缩放的问题

### ISSUE THREAD

**Issue by HelloLollipop** [ongakuer/PhotoDraweeView#30]
就是加载动画的这个壁纸也可以手势缩放，正常操作是不应该缩放的吧

**Comment by ongakuer** [comment]
你是使用哪种方式加载图片的？

1. 用```setPhotoUri```的话 ，应该不会出现这个问题。 

2. 如果是自定义 ControllerBuilder 加载，你可以参考一下  [```setPhotoUri```] (https://github.com/ongakuer/PhotoDraweeView/blob/master/photodraweeview/src/main/java/me/relex/photodraweeview/PhotoDraweeView.java#L168) 的源码。
使用 [```setEnableDraweeMatrix ```](https://github.com/ongakuer/PhotoDraweeView/blob/master/photodraweeview/src/main/java/me/relex/photodraweeview/PhotoDraweeView.java#L159) 来禁止加载期间的缩放。
