### ISSUE TITLE
左右切换要滑动很长距离才能成功

### ISSUE THREAD

**Issue by liujinchaoDS** [ongakuer/PhotoDraweeView#31]
在MultiTouchViewPager左右滑动切换图片时，至少要滑动2/3才能切换成功，单手很难操作，如何设置可以滑动1/3即可左右切换？

**Comment by ongakuer** [comment]
这个是ViewPager默认控制。与项目无关。

**Comment by liujinchaoDS** [comment]
ViewPager只需要1/3就可以划过去，所以不是ViewPager的问题

**Comment by ongakuer** [comment]
或者你可以换成 [HackyViewPager](https://github.com/chrisbanes/PhotoView/blob/master/sample/src/main/java/uk/co/senab/photoview/sample/HackyViewPager.java) 试试
