### ISSUE TITLE
使用viewpage嵌套的情况下,双指缩小图片然后立刻左右滑动切换viewpage 的时候会出现异常

### ISSUE THREAD

**Issue by Roing** [ongakuer/PhotoDraweeView#32]
使用viewpage嵌套的情况下,双指缩小图片然后立刻左右滑动切换viewpage 的时候会出现异常          java.lang.IllegalArgumentException: pointerIndex out of range pointerIndex=-1 pointerCount=1

**Comment by ongakuer** [comment]
https://github.com/ongakuer/PhotoDraweeView/issues/28

**Comment by ongakuer** [comment]
https://github.com/ongakuer/PhotoDraweeView/issues/28
