### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Jucongyuan** [ongakuer/PhotoDraweeView#35]
1 android.view.MotionEvent.nativeGetAxisValue(Native Method)
2 android.view.MotionEvent.getX(MotionEvent.java:1979)
3 android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2064)
4 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1859)
5 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
6 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
7 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
8 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
9 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
10 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
11 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
12 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
13 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
14 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
15 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
16 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
17 com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2101)
18 com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1548)
19 android.app.Activity.dispatchTouchEvent(Activity.java:2510)
20 android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
21 com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2049)
22 android.view.View.dispatchPointerEvent(View.java:7914)
23 android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4280)
24 android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4159)
25 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3657)
26 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3707)
27 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3676)
28 android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3783)
29 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3684)
30 android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3840)
31 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3657)
32 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3707)
33 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3676)
34 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3684)
35 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3657)
36 android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5865)
37 android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5845)
38 android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5816)
39 android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5956)
40 android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
41 android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
42 android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
43 android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5918)
44 android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5979)
45 android.view.Choreographer$CallbackRecord.run(Choreographer.java:787)
46 android.view.Choreographer.doCallbacks(Choreographer.java:600)
47 android.view.Choreographer.doFrame(Choreographer.java:567)
48 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:773)
49 android.os.Handler.handleCallback(Handler.java:733)
50 android.os.Handler.dispatchMessage(Handler.java:95)
51 android.os.Looper.loop(Looper.java:136)
52 android.app.ActivityThread.main(ActivityThread.java:5336)
53 java.lang.reflect.Method.invokeNative(Native Method)
54 java.lang.reflect.Method.invoke(Method.java:515)
55 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
56 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
57 dalvik.system.NativeStart.main(Native Method)

**Comment by ongakuer** [comment]
https://github.com/ongakuer/PhotoDraweeView#issues-with-viewgroups

https://github.com/ongakuer/PhotoDraweeView/blob/master/sample/src/main/java/me/relex/photodraweeview/sample/MultiTouchViewPager.java
