### ISSUE TITLE
提个优化建议，实现自定义缩放级别

### ISSUE THREAD

**Issue by interchen** [ongakuer/PhotoDraweeView#37]
目前缩放分三级，min，mid，max，但是这样很不灵活，昨天我为了实现只有两级缩放，几乎把 Attacher, OnDoubleTapListener, HKPhotoDraweeView 都实现了一遍
但其实要实现改动还是蛮小的，只需要将 min, mid, max 模型修改为 min, step, max 模型即可，用户就可以自定义任意级别的缩放了
如果你觉得可行的话，我来修改提交 PR

**Comment by ongakuer** [comment]
欢迎提交。
这个为了保持 PhotoView 一致、兼容旧版，所以需要```(min, step, max)```  兼容 ```(min, mid, max)```

**Comment by ongakuer** [comment]
https://github.com/ongakuer/PhotoDraweeView/pull/39
