### ISSUE TITLE
 Attacher中如何在横屏状态下，保持宽度铺满，高度可以滚动?

### ISSUE THREAD

**Issue by weizai** [ongakuer/PhotoDraweeView#4]
对于最新PhotoView代码库，通过修改updateBaseMatrix方法中的mBaseMatrix.setRectToRect 可以实现，那对于PhotoDraweeView如何修改?

**Comment by ongakuer** [comment]
目前只有默认的居中缩放模式。 通过设定Matrix应该也能设置不同的缩放模式。 PhotoView好像是通过两个Matrix组合处理的，方便扩展。 我这简化成一个了， 你可以试试处理Matrix变化。
