### ISSUE TITLE
作者这个缩放还原功能吗，暴露出的一个方法

### ISSUE THREAD

**Issue by xiedong** [ongakuer/PhotoDraweeView#40]
作者我这边有个这样的使用场景，一个VIEWPAGER，里面有俩个VIEW，VIEW1切转VIEW2，现在是情景是，进入VIEW1的时候我把VIEW1里面的图片手动拉大，之后切转VIEW2，之后再切回VIEW1，当再次看到这个VIEW1的时候，需要把这个之前拉大的图片还原回原来大小（这个需要提前，再切回之前）

**Comment by ongakuer** [comment]
调用 ```setScale()```，放大回1f 就行了吧
https://github.com/ongakuer/PhotoDraweeView/blob/master/photodraweeview/src/main/java/me/relex/photodraweeview/PhotoDraweeView.java#L106

**Comment by ongakuer** [comment]
至于调用的时机，你看一下 Viewpager 的相关回调。

**Comment by xiedong** [comment]
谢谢
