### ISSUE TITLE
如何让图片默认是宽度撑满整个屏幕，高度再自适应

### ISSUE THREAD

**Issue by interchen** [ongakuer/PhotoDraweeView#41]
如何让图片默认是宽度撑满整个屏幕，高度再自适应

**Comment by ongakuer** [comment]
fresco的缩放机制是内部实现的。没有找到合适的方法通过在 ```onDraw``` 中通过矩阵缩放。

**Comment by interchen** [comment]
实现了！在`instantiateItem`里将`photoDraweeView`放到 ScrollView 中，动态根据`photoDraweeView`的宽高调整`LayoutParams`即可实现

**Comment by CaiPeng** [comment]
@interchen  能否 把代码贴一下

**Comment by CaiPeng** [comment]
@ongakuer @interchen   我也遇到了这个问题  需求和这个差不多，将photoDraweeView放入RecyclerView，设置缩放模式  也不太好使

**Comment by interchen** [comment]
单个 item 的 layout
<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <me.relex.photodraweeview.PhotoDraweeView
            android:id="@+id/photoDraweeView"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </LinearLayout>
</ScrollView>

最后在`setControllerListener`的`onFinalImageSet`中调整高宽即可

**Comment by softrice** [comment]
能否在获得图片宽高后 
也就是在 mAttacher.update(imageInfoWidth, imageInfoHeight); 中初始化
对于一些长图,现象是先小图 后面又缩放成大图

**Comment by r17171709** [comment]
@interchen 能否提供一下代码？我发现PhotoDraweeView就算是全屏也没有用，长图依然被自适应了

**Comment by interchen** [comment]
@r17171709 代码已经在上面提供了啊

**Comment by r17171709** [comment]
@interchen 我还是没有实现。。。
