### ISSUE TITLE
我测试了下，貌似这个把所有的监听时间都拦截了

### ISSUE THREAD

**Issue by xiedong** [ongakuer/PhotoDraweeView#42]
用了N种办法 点击这个图片 实现一个监听 所触控的方法 结果各种尝试 通通拦截掉了

**Comment by ongakuer** [comment]
不太明白你需要场景是什么，控件本身已经提供了下面这些事件监听

```
setOnDoubleTapListener
setOnScaleChangeListener
setOnLongClickListener
setOnPhotoTapListener
setOnViewTapListener
```

**Comment by xiedong** [comment]
亲爱的作者，是这样的，我们有一个需求，就是点击图片区域，图片上部分的titlebar 会隐藏，再次点击就会显示，我用了很多方法去调这个点击监听，比如重写ONTOUCH 方法盘点DOEN和UP，还有给这个您写的自定义VIEW 一个SETOCLICKLIS的监听方法，结果这个俩个方法均失效

**Comment by ongakuer** [comment]
点击图片区域你用 ```setOnPhotoTapListener```就好了

**Comment by xiedong** [comment]
哦哦，好的，谢谢作者，我实验下

**Comment by xiedong** [comment]
setOnLongClickListener
setOnPhotoTapListener
我把你写的控件放到VIEWPAGER 里 都失效了 这俩方法

**Comment by xiedong** [comment]
package com.android.lft.block.main.fkb.view;

import android.content.Context;
import android.net.Uri;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.android.lft.R;
import com.android.lft.block.main.RecyclingPagerAdapter;
import com.android.lft.block.main.fkb.bean.FkbPaymentVoucherListViewModel;

import java.util.ArrayList;
import java.util.List;

import butterknife.BindView;
import butterknife.ButterKnife;
import me.relex.photodraweeview.OnPhotoTapListener;
import me.relex.photodraweeview.PhotoDraweeView;

/**
 * @ClassName: FkbPaymentVoucherAdapter
 * @Description: 付款凭证适配器
 * @author: xiedong
 * @date: 2016/10/17 15:48
 */
public class FkbPaymentVoucherAdapter extends RecyclingPagerAdapter implements OnPhotoTapListener, View.OnLongClickListener {
    private Context mContext;
    private List<FkbPaymentVoucherListViewModel.Ehlist> data = new ArrayList<FkbPaymentVoucherListViewModel.Ehlist>();
    private FkbPaymentVoucherAdapter.ViewHolder holder;
    private OnClickCallBack mOnClickCallBack;

    public FkbPaymentVoucherAdapter(Context mContext, List<FkbPaymentVoucherListViewModel.Ehlist> data, OnClickCallBack mOnClickCallBack) {
        this.mContext = mContext;
        this.data = data;
        this.mOnClickCallBack = mOnClickCallBack;
    }

    public View getView(final int position, View convertView, ViewGroup container) {
        if (convertView != null) {
            holder = (FkbPaymentVoucherAdapter.ViewHolder) convertView.getTag();
            holder.simpleView.setOnPhotoTapListener(this);
            holder.simpleView.setOnLongClickListener(this);
            holder.simpleView.setClickable(true);
        } else {
            convertView = LayoutInflater.from(mContext).inflate(R.layout.lft_item_fkb_payment_vocher_page, container, false);
            holder = new FkbPaymentVoucherAdapter.ViewHolder(convertView);
            convertView.setTag(holder);
        }
        if (0 == data.size()) return convertView;
        Uri uri = Uri.parse(String.valueOf(data.get(position).getVoucherUrl()));
        holder.simpleView.setPhotoUri(uri);
        return convertView;
    }

    @Override
    public int getCount() {
        return null == data ? 0 : data.size();
    }

    @Override
    public void onPhotoTap(View view, float x, float y) {
        mOnClickCallBack.OnClick();
    }

    @Override
    public boolean onLongClick(View v) {
        mOnClickCallBack.OnLongClick();
        return false;
    }


    static class ViewHolder {
        @BindView(R.id.simple_view)
        PhotoDraweeView simpleView;

        ViewHolder(View view) {
            ButterKnife.bind(this, view);
        }
    }

    public void setScale() {
        holder.simpleView.setScale(1f);
    }

    public interface OnClickCallBack {
        void OnLongClick();

        void OnClick();
    }
}

**Comment by xiedong** [comment]
断点测试那俩 监听没触发 是否还需要别的条件？

**Comment by xiedong** [comment]
我怀疑是否有什么 控件把这个监听给拦截了

**Comment by ongakuer** [comment]
你把 ```setClickable``` 去掉试试？

Viewpager 中是能正常监听到事件的。 你可以在 sample 中 下面这行加入
https://github.com/ongakuer/PhotoDraweeView/blob/master/sample/src/main/java/me/relex/photodraweeview/sample/ViewPagerActivity.java#L77

```
 photoDraweeView.setOnPhotoTapListener(new OnPhotoTapListener() {
                @Override public void onPhotoTap(View view, float x, float y) {
                    Toast.makeText(view.getContext(), "onPhotoTap x= " + x + " y = " + y,
                            Toast.LENGTH_SHORT).show();
                }
            });
```

可以接受到事件监听。

**Comment by xiedong** [comment]
好使了，作者，是我写错了监听位置，谢谢您了

**Comment by musicode** [comment]
监听图片下载成功或失败，是这样的么？

```
private void setUrl(String url) {
        PipelineDraweeControllerBuilder controller = Fresco.newDraweeControllerBuilder();

        mPhotoView.setController(
                controller
                    .setUri(url)
                    .setControllerListener(new BaseControllerListener<ImageInfo>() {
                        public void onFailure(String id, Throwable throwable) {
                            super.onFailure(id, throwable);
                            Log.d("LOAD", "failed");
                        }

                        public void onIntermediateImageSet(String id, ImageInfo imageInfo) {
                            super.onIntermediateImageSet(id, imageInfo);
                            Log.d("LOAD", "success");
                        }
                    })
                    .build()
}
```

但是事件没触发啊

**Comment by ongakuer** [comment]
@musicode 

https://www.fresco-cn.org/docs/listening-download-events.html

```onIntermediateImageSet``` 是渐进图片下载

成功应该用```onFinalImageSet```

**Comment by musicode** [comment]
图片下好之后，模拟器里双击鼠标没有反应啊，PhotoView 是可以的呢

**Comment by musicode** [comment]
模拟器里的缩放怎么测试呢？
