### ISSUE TITLE
 holder.photoDraweeView.setPhotoUri(uri, mContext); 没有回调图片问题

### ISSUE THREAD

**Issue by xiedong** [ongakuer/PhotoDraweeView#43]
作者，我需要你这个方法   holder.photoDraweeView.setPhotoUri(uri, mContext); 回调一个 加载成功后的图片资源，我如果我继承你的PhotoDraweeView类，但是 你那个方法里我无法改变你的    private boolean mEnableDraweeMatrix = true; 这个参数，因为它是私有的，如果我直接复制一遍的话，有一个错误就是
  @Override protected void onDetachedFromWindow() {
        mAttacher.onDetachedFromWindow();
        super.onDetachedFromWindow();
    }这个方法里的  mAttacher.onDetachedFromWindow();  这个方法是被保护的，不允许我去调用，求解。

**Comment by xiedong** [comment]
难道必须要弄成MODEL 模式 O.O

**Comment by xiedong** [comment]
如果直接用FRECO 自己带的，图片的缩放功能就会失去效果，我看你写了 一个这样的方法，估计就是改那里了

**Comment by ongakuer** [comment]
```setEnableDraweeMatrix``` 有这个方法……

**Comment by xiedong** [comment]
嗯 谢谢 我刚才发现了 你写了这个方法

**Comment by xiedong** [comment]
作者 调用这个   public void setPhotoUri(Uri uri, @Nullable Context context)  方法 我加载了 俩张图片  第一张无法 手势缩放，第二张才可以

**Comment by xiedong** [comment]
public void setPhotoUri(Uri uri, @Nullable Context context) {
        holder.photoDraweeView.setEnableDraweeMatrix(false);
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setCallerContext(context)
                .setUri(uri)
                .setOldController(holder.photoDraweeView.getController())
                .setControllerListener(new BaseControllerListener<ImageInfo>() {
                    @Override
                    public void onFailure(String id, Throwable throwable) {
                        super.onFailure(id, throwable);
                        holder.photoDraweeView.setEnableDraweeMatrix(false);
                    }

                    @Override
                    public void onFinalImageSet(String id, ImageInfo imageInfo,
                                                Animatable animatable) {
                        super.onFinalImageSet(id, imageInfo, animatable);
                        holder.photoDraweeView.setEnableDraweeMatrix(true);
                        if (imageInfo != null) {
                            holder.photoDraweeView.update(imageInfo.getWidth(), imageInfo.getHeight());
                        }
                    }

                    @Override
                    public void onIntermediateImageFailed(String id, Throwable throwable) {
                        super.onIntermediateImageFailed(id, throwable);
                        holder.photoDraweeView.setEnableDraweeMatrix(false);
                    }

                    @Override
                    public void onIntermediateImageSet(String id, ImageInfo imageInfo) {
                        super.onIntermediateImageSet(id, imageInfo);
                        holder.photoDraweeView.setEnableDraweeMatrix(true);
                        if (imageInfo != null) {
                            holder.photoDraweeView.update(imageInfo.getWidth(), imageInfo.getHeight());
                        }
                    }
                })
                .build();
        holder.photoDraweeView.setController(controller);
    }   我写的和你一模一样

**Comment by xiedong** [comment]
貌似   只好 第一行  默认 改成   holder.photoDraweeView.setEnableDraweeMatrix(true); 能缩放了

**Comment by xiedong** [comment]
测试了下 也不好使

**Comment by xiedong** [comment]
这个监听 也失效了 holder.photoDraweeView.setOnPhotoTapListener(this);

**Comment by xiedong** [comment]
用这个方法，手势缩放就失效。
 private void setPhotoUri(Uri uri) {
        ImageRequest imageRequest = ImageRequestBuilder
                .newBuilderWithSource(uri)
                .setProgressiveRenderingEnabled(true).build();
        Fresco.getImagePipeline().fetchDecodedImage(imageRequest, this).subscribe(new BaseBitmapDataSubscriber() {
            @Override
            public void onNewResultImpl(@Nullable Bitmap bitmap) {
                if (null != bitmap) {

                }
            }

            @Override
            public void onFailureImpl(DataSource dataSource) {

            }
        }, CallerThreadExecutor.getInstance());
        ControllerListener controllerListener = new BaseControllerListener<ImageInfo>() {
            @Override
            public void onFinalImageSet(String id, @Nullable ImageInfo imageInfo, @Nullable Animatable anim) {
                holder.photoDraweeView.setEnableDraweeMatrix(true);
            }

            @Override
            public void onFailure(String id, Throwable throwable) {
                holder.photoDraweeView.setEnableDraweeMatrix(false);
            }
        };
        DraweeController draweeController = Fresco.newDraweeControllerBuilder()
                .setAutoPlayAnimations(true)
                .setImageRequest(imageRequest)
                .setControllerListener(controllerListener)
                .build();
        holder.photoDraweeView.setController(draweeController);
    }

**Comment by ongakuer** [comment]
如果单独拿出来是可以使用的，可能是你的pager adapter 回收等原因没有处理好 setEnableDraweeMatrix

**Comment by xiedong** [comment]
好的，这个问题解决了，为此贴上源码
 public void setPhotoUri(Uri uri) {
        ImageRequest imageRequest = ImageRequestBuilder
                .newBuilderWithSource(uri).setResizeOptions(new ResizeOptions(400, 400))
                .setProgressiveRenderingEnabled(true).build();
        ImagePipeline imagePipeline = Fresco.getImagePipeline();
        DataSource<CloseableReference<CloseableImage>> dataSource = imagePipeline.fetchDecodedImage(imageRequest, this);
        dataSource.subscribe(new BaseBitmapDataSubscriber() {
            @Override
            public void onNewResultImpl(@Nullable Bitmap bitmap) {
                if (null != bitmap) {
                }
            }

            @Override
            public void onFailureImpl(DataSource dataSource) {

            }
        }, CallerThreadExecutor.getInstance());
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setCallerContext(mContext)
                .setUri(uri)
                .setImageRequest(imageRequest)
                .setOldController(holder.photoDraweeView.getController())
                .setControllerListener(new BaseControllerListener<ImageInfo>() {
                    @Override
                    public void onFailure(String id, Throwable throwable) {
                        super.onFailure(id, throwable);
                        holder.photoDraweeView.setEnableDraweeMatrix(false);
                    }

                    @Override
                    public void onFinalImageSet(String id, ImageInfo imageInfo,
                                                Animatable animatable) {
                        super.onFinalImageSet(id, imageInfo, animatable);
                        holder.photoDraweeView.setEnableDraweeMatrix(true);
                        if (imageInfo != null) {
                            holder.photoDraweeView.update(imageInfo.getWidth(), imageInfo.getHeight());
                        }
                    }

                    @Override
                    public void onIntermediateImageFailed(String id, Throwable throwable) {
                        super.onIntermediateImageFailed(id, throwable);
                        holder.photoDraweeView.setEnableDraweeMatrix(false);
                    }

                    @Override
                    public void onIntermediateImageSet(String id, ImageInfo imageInfo) {
                        super.onIntermediateImageSet(id, imageInfo);
                        holder.photoDraweeView.setEnableDraweeMatrix(true);
                        if (imageInfo != null) {
                            holder.photoDraweeView.update(imageInfo.getWidth(), imageInfo.getHeight());
                        }
                    }
                })
                .build();
        holder.photoDraweeView.setController(controller);
        imagePipeline.evictFromDiskCache(uri);

    }
