### ISSUE TITLE
holder.photoDraweeView.setOnViewTapListener(this);拦截了子控件监听问题

### ISSUE THREAD

**Issue by xiedong** [ongakuer/PhotoDraweeView#44]
这个监听时间是否优先级太高了，里面有没有设置getParent().requestDisallowInterceptTouchEvent(true) 类似这个的方法，我感觉你这个监听时间不是PhotoDraweeView的监听事件，而是整个屏幕的事件，结果把PhotoDraweeView隐藏掉，给另外一个VIEW写一个ONCLICK监听事件，结果每次都执行holder.photoDraweeView.setOnViewTapListener(this)监听，被拦截了

**Comment by ongakuer** [comment]
另一个控件的先后顺序是不是错了？ 试试另一个控件放在PhotoDraweeView上面应该不会拦截的。

OnViewTapListener 是通过 GestureDetector 的 onSingleTapConfirmed 实现的。 
https://github.com/ongakuer/PhotoDraweeView/blob/master/photodraweeview/src/main/java/me/relex/photodraweeview/DefaultOnDoubleTapListener.java#L17

如果你需要试试其他实现方式，可以自定义一个 DoubleTapListener 来处理

**Comment by xiedong** [comment]
产品的需求太坑，唉，一个图片加载要搞那么多功能，要图片上面的TITLEVAR 点击 这个 整个POP 会收缩，而且是一个VIEWPAGER 包含多张页，还有一种情况就是要带滑动，缩放，如果加载异常还得点击能重新获取图片，FRECO 上的根本不行，我是自己写的
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fresco="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <me.relex.photodraweeview.PhotoDraweeView
        android:id="@+id/simple_view"
        android:layout_width="@dimen/w700"
        android:layout_height="@dimen/h1080"
        android:layout_gravity="center"
        fresco:actualImageScaleType="centerCrop"
        fresco:progressBarAutoRotateInterval="1000"
        fresco:progressBarImage="@drawable/progressdialog"
        fresco:progressBarImageScaleType="centerInside" />

    <com.android.lft.widget.CustomFontTextView
        android:id="@+id/txt_progress"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:layout_marginTop="@dimen/h80"
        android:text="@string/text_image_loading_please_later"
        android:textColor="@color/color_999999"
        android:textSize="@dimen/h28"
        android:visibility="gone" />

    <include layout="@layout/base_layout_image_unusual_view" />
</FrameLayout>

**Comment by ongakuer** [comment]
你是需要加载失败点击重新加载?

**Comment by xiedong** [comment]
对的

**Comment by xiedong** [comment]
这个东西和这个VIEW 还有这个VIEWPAGER 各种冲突

**Comment by xiedong** [comment]
我是一个VIEWPAGER 里套了 一个 XML  XML 就是上面发的

**Comment by ongakuer** [comment]
ViewPager 需要处理一下[兼容问题](https://github.com/ongakuer/PhotoDraweeView/blob/master/sample/src/main/java/me/relex/photodraweeview/sample/MultiTouchViewPager.java)

加载出错，可以使用 fresco 自带属性显示出错图片。 然后使用ControllerBuilder 监听出错情况，动态设置 setOnViewTapListener 点击重新加载。

**Comment by xiedong** [comment]
fresco 自带属性显示出错图片 点击连续 加载出错四次就会出现失败图片，我们产品的意思是 一直出错，坑，还有就是setOnViewTapListener 这个监听的时候 必须收缩POP，不能干别的，所以我单独写了个异常布局，从隐藏变显示把PhotoDraweeView挤下去，结果VIEWPAGER又与 这个异常VIEW 冲突了，快崩溃了

**Comment by xiedong** [comment]
fresco 自带属性显示出错图片 点击连续 加载出错四次就会出现失败图片，我们产品的意思是 一直出错，坑，还有就是setOnViewTapListener 这个监听的时候 必须收缩POP，不能干别的，所以我单独写了个异常布局，从隐藏变显示把PhotoDraweeView挤下去，结果VIEWPAGER又与 这个异常VIEW 冲突了，快崩溃了

**Comment by xiedong** [comment]
public void setPhotoUri(Uri uri, final int position) {
        holder.txtProgress.setVisibility(View.VISIBLE);
        this.uri = uri;
        this.postion = position;
        ImageRequest imageRequest = ImageRequestBuilder
                .newBuilderWithSource(uri).setResizeOptions(new ResizeOptions(400, 400))
                .build();
        ImagePipeline imagePipeline = Fresco.getImagePipeline();
        DataSource<CloseableReference<CloseableImage>> dataSource = imagePipeline.fetchDecodedImage(imageRequest, this);
        dataSource.subscribe(new BaseBitmapDataSubscriber() {
            @Override
            public void onNewResultImpl(@Nullable Bitmap bitmap) {
                if (null != bitmap) {
                    if (!chaceBitmapData.containsKey(String.valueOf(position)) && !chaceBitmapData.containsValue(bitmap)) {
                        chaceBitmapData.put(String.valueOf(position), bitmap);
                    }
                }
            }

            @Override
            public void onFailureImpl(DataSource dataSource) {
            }
        }, CallerThreadExecutor.getInstance());
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setCallerContext(mContext)
                .setImageRequest(imageRequest).setTapToRetryEnabled(true)
                .setOldController(holder.photoDraweeView.getController())
                .setControllerListener(new BaseControllerListener<ImageInfo>() {
                    @Override
                    public void onFailure(String id, Throwable throwable) {
                        super.onFailure(id, throwable);
                        holder.txtProgress.setVisibility(View.GONE);
                        holder.rlayoutUnusual.setVisibility(View.VISIBLE);
                        holder.photoDraweeView.setEnableDraweeMatrix(false);
                    }

                    @Override
                    public void onFinalImageSet(String id, ImageInfo imageInfo,
                                                Animatable animatable) {
                        super.onFinalImageSet(id, imageInfo, animatable);
                        holder.txtProgress.setVisibility(View.GONE);
                        holder.rlayoutUnusual.setVisibility(View.GONE);
                        holder.photoDraweeView.setEnableDraweeMatrix(true);
                        if (imageInfo != null) {
                            holder.photoDraweeView.update(imageInfo.getWidth(), imageInfo.getHeight());
                        }
                    }

                    @Override
                    public void onIntermediateImageFailed(String id, Throwable throwable) {
                        super.onIntermediateImageFailed(id, throwable);
                        holder.photoDraweeView.setEnableDraweeMatrix(false);
                    }

                    @Override
                    public void onIntermediateImageSet(String id, ImageInfo imageInfo) {
                        holder.photoDraweeView.setEnableDraweeMatrix(true);
                        if (imageInfo != null) {
                            holder.photoDraweeView.update(imageInfo.getWidth(), imageInfo.getHeight());
                        }
                    }
                })
                .build();
        holder.photoDraweeView.setController(controller);
        imagePipeline.evictFromDiskCache(uri);

    }

**Comment by xiedong** [comment]
点击重新加载图

在加载失败时，可以设置点击重新加载。这时提供一个图片，加载失败时，会显示这个图片（而不是失败提示图片），提示用户点击重试。

在ControllerBuilder 中如下设置:

1

	

.setTapToRetryEnabled(true)

加载失败时，image pipeline 会重试四次；如果还是加载失败，则显示加载失败提示图片。 用这个方法好像滑动监听会拦截这个监听

**Comment by ongakuer** [comment]
fresco  的 点击事件都会被拦截掉 ，所以设置  setTapToRetryEnabled  无效的。
你需要自己处理点击逻辑

**Comment by xiedong** [comment]
哦，好的，谢谢作者了，我这样尝试一下

**Comment by xiedong** [comment]
viewPager默认缓存2页
适配器 初始化的时候执行了2次 getView
下面方法执行了俩次
 DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setCallerContext(mContext)
                .setImageRequest(imageRequest)
                .setOldController(holder.photoDraweeView.getController())
                .setControllerListener(new BaseControllerListener<ImageInfo>() {
                    @Override
                    public void onFailure(String id, Throwable throwable) {
                        super.onFailure(id, throwable);
                        holder.photoDraweeView.setEnableDraweeMatrix(false);
                        holder.txtProgress.setVisibility(View.GONE);
                        holder.rlayoutUnusual.setVisibility(View.VISIBLE);
                    }

                    @Override
                    public void onFinalImageSet(String id, ImageInfo imageInfo,
                                                Animatable animatable) {
                        super.onFinalImageSet(id, imageInfo, animatable);
                        holder.photoDraweeView.setEnableDraweeMatrix(true);
                        holder.txtProgress.setVisibility(View.GONE);
                        holder.rlayoutUnusual.setVisibility(View.GONE);
                        if (imageInfo != null) {
                            holder.photoDraweeView.update(imageInfo.getWidth(), imageInfo.getHeight());
                        }
                    }


   holder.photoDraweeView.setEnableDraweeMatrix(true);这个方法只有VIEWPAGER 里 第二个生效了
  第一个          holder.photoDraweeView.setEnableDraweeMatrix(true);
                        holder.txtProgress.setVisibility(View.GONE);
                        holder.rlayoutUnusual.setVisibility(View.GONE);这三方法都没生效，
我怀疑是 VIEWPAGER给第二个页面重复执行了俩次
 holder.photoDraweeView.setEnableDraweeMatrix(true);
                        holder.txtProgress.setVisibility(View.GONE);
                        holder.rlayoutUnusual.setVisibility(View.GONE);这三个方法或者干脆第一个界面执行失效，作者您有什么好的思路没有？

**Comment by xiedong** [comment]
界面的实际显示效果就是    VIEWPAGER里第一个 界面的 缩放监听开关 开启和文字隐藏都失效      导致第一个界面  文字没消失  手势缩放监听不好使

**Comment by xiedong** [comment]
ViewPager预加载是3页，可以取消预加载，但是滑动页面会卡，不推荐。
试着用另一个思路做：viewpager有一个setOnPageChangeListener监听，这个监听可以知道当前滑动的是哪一页，设置个回调，当滑动到这一页的时候做相应的页面处理，而不是把所有东西都丢进oncreate onreseme里面做。 这个是别人提的方案 我尝试下
