### ISSUE TITLE
小米MAX上出现缩放重影的现象

### ISSUE THREAD

**Issue by tulongchao** [ongakuer/PhotoDraweeView#45]
在小米手机上线放大图片，在用双指缩小，出现重影的现象
![test](https://cloud.githubusercontent.com/assets/6149241/19758667/b65f012c-9c5b-11e6-8a88-61057208855e.jpg)

**Comment by ongakuer** [comment]
Sample 是否出现同样的情况？

**Comment by tanshion** [comment]
![image](https://cloud.githubusercontent.com/assets/9196558/20738129/057bc024-b6ec-11e6-97b1-8f711a470906.png)

**Comment by tanshion** [comment]
![image](https://cloud.githubusercontent.com/assets/9196558/20738133/141359a8-b6ec-11e6-8a9b-0672eb961998.png)
在class Attacher 的checkMatrixAndInvalidate() 添加draweeView.getRootView().invalidate();可以解决

**Comment by ongakuer** [comment]
我这边使用 Android 6.0 并没有出现重影，小米5也没有出现。  出现截图的情况可能与你在使用 PhotoDraweeView 时外层的 Layout 有关系。 

调用 ```draweeView.getRootView().invalidate()``` ，通知 RootView 重绘的解决办法不太友好，对于已经使用这个控件的用户可能会有性能影响。 

如果一定要刷新外层view，可以试试在外部调用  ```draweeView.getViewTreeObserver().addOnPreDrawListener(listener)```，在 listener 内部通知 RootView 重绘

**Comment by tulongchao** [comment]
按照你的方法确实确实解决了，这个现在在vivo X7上也会出现的

**Comment by tulongchao** [comment]
还是要感谢一下啊。

**Comment by ongakuer** [comment]
不客气
