### ISSUE TITLE
显示本地图片在的手机上会非常卡顿

### ISSUE THREAD

**Issue by longhunpeter** [ongakuer/PhotoDraweeView#46]

**Comment by ongakuer** [comment]
卡顿是缩放卡顿吗？ 可能不适用加载超大图

**Comment by ikkyu0319** [comment]
加载本地图片，的确很卡顿~~

**Comment by chenlindaydayup** [comment]
用在viewpage上会卡顿 估计是图片稍微大点内存就溢出了

**Comment by ongakuer** [comment]
http://frescolib.org/docs/resizing-rotating.html
加载本地图片可能需要使用  ```setDownsampleEnabled(true)```
