### ISSUE TITLE
手势缩放横拉没有用。。。

### ISSUE THREAD

**Issue by qq332769043** [ongakuer/PhotoDraweeView#50]
是什么原因呢  是和切换的手势冲突么。。。。两根手指横拉图片不能放大，但斜着拉，竖着拉就可以

**Comment by luxiao0314** [comment]
两根手指横拉图片不能放大,这个问题楼主想到办法解决了吗

**Comment by ongakuer** [comment]
可能是走进了拖动的判断里。
https://github.com/ongakuer/PhotoDraweeView/blob/master/photodraweeview/src/main/java/me/relex/photodraweeview/ScaleDragDetector.java#L149

**Comment by ongakuer** [comment]
@qq332769043 @luxiao0314 
测试了一下，单独使用PhotoDraweeView没有出现这种情况吧？ 

放入 ViewPager 后双指横拉会触发 ViewPager 的切换事件。 
如果你们是使用 sample 里的 MultiTouchViewPager的话，可能[这里]( https://github.com/ongakuer/PhotoDraweeView/blob/master/sample/src/main/java/me/relex/photodraweeview/sample/MultiTouchViewPager.java#L27)事件拦截判断的逻辑得重新调整一下…

可以试试用 try 的方式拦截事件冲突崩溃： https://github.com/chrisbanes/PhotoView#issues-with-viewgroups
