### ISSUE TITLE
New release for fresco 1.0.0

### ISSUE THREAD

**Issue by Huulivoide** [ongakuer/PhotoDraweeView#52]
Could you please make a new release of the library that uses the dependencies I updated about a month ago?

**Comment by ongakuer** [comment]
Just update fresco to latest version.  The released library doesn't care about fresco version.

```
dependencies {
    compile 'com.facebook.fresco:fresco:1.0.1'
    compile 'me.relex:photodraweeview:1.1.2'
}
```
![wx20170203-195839](https://cloud.githubusercontent.com/assets/1284428/22590812/072d6ef2-ea4c-11e6-8ed9-9f8bda3138bd.png)
