### ISSUE TITLE
默认图片

### ISSUE THREAD

**Issue by amyliu1062** [ongakuer/PhotoDraweeView#54]
加载网络图片，在为下载成功时，想显示一张默认图片，不知怎么显示

**Comment by ongakuer** [comment]
https://github.com/ongakuer/PhotoDraweeView/blob/master/sample/src/main/res/layout/activity_single.xml#L13

**Comment by amyliu1062** [comment]
@ongakuer 是在动态代码如何设置？

`final PhotoDraweeView photoDraweeView = new PhotoDraweeView(viewGroup.getContext());
            PipelineDraweeControllerBuilder controller = Fresco.newDraweeControllerBuilder();
            controller.setUri(urls.get(position));
            controller.setRetainImageOnFailure(true);
            controller.setOldController(photoDraweeView.getController());`

**Comment by ongakuer** [comment]
前面说的是xml中设置。

占位图设置参见官方文档 http://frescolib.org/docs/using-drawees-code.html
```
hierarchy.setPlaceholderImage(R.drawable.placeholderId);
```

**Comment by amyliu1062** [comment]
@ongakuer 知道了。谢谢。还有一个问题，我看demo中加载图片时是有一个圆形进度条的，但是我的代码没有，有可能是哪里需要设置吗？

**Comment by ongakuer** [comment]
同样是xml 设置 进度条
https://github.com/ongakuer/PhotoDraweeView/blob/master/sample/src/main/res/layout/activity_single.xml#L16

**Comment by amyliu1062** [comment]
哦哦，谢谢。 @ongakuer
