### ISSUE TITLE
Zooming does not take effect until app is hidden and shown again

### ISSUE THREAD

**Issue by josephlam1984** [ongakuer/PhotoDraweeView#55]
Hello,

I am currently using PhotoDraweeView in a FragmentStatePagerAdapter with a ViewPager.

I can pinch in and out of an image but it does not zoom in or zoom out until the app is hidden and shown again (i.e. zoom in on the image, the image still looks the same, now press home to hide the app, and then go back to the app, the image is now zoomed in).

Here is my code in the XML layout:
    <me.relex.photodraweeview.PhotoDraweeView
        android:id="@+id/image"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_centerInParent="true"
        android:adjustViewBounds="true"
        android:background="@android:color/white"
        fresco:actualImageScaleType="fitCenter"
        fresco:failureImage="@mipmap/error_small" />

Thanks,
Joseph

**Comment by josephlam1984** [comment]
Resolved the comment by placing the update code in onFinalImageSet:

                        @Override
                        public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
                            imageView.update(imageInfo.getWidth(), imageInfo.getHeight());
                        }

**Comment by FazliMolaJan** [comment]
I also have the same problem, what you did with this error? Please explain me.
