### ISSUE TITLE
Released Under What License?

### ISSUE THREAD

**Issue by milkrun** [ongakuer/PhotoDraweeView#7]
Hey there,

I like this library and would like to use it. What license is it released under?
Would you please add something making the license explicit?
Thanks,
Milk Run

**Comment by ongakuer** [comment]
Thank you for reminding me.
[Apache-2.0](http://opensource.org/licenses/apache2.0.php)

**Comment by milkrun** [comment]
Thank you. Would you please put something in the project. Maybe put it in the ReadMe?
Thank you again.

**Comment by ongakuer** [comment]
BTW, You need upgrade Fresco to latest version.
