### ISSUE TITLE
JCenter sunsetting

### ISSUE THREAD

**Issue by carltonwhitehead** [ongakuer/PhotoDraweeView#81]
JCenter is sunsetting on Feb 1, 2022, per https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

PhotoDraweeView is published on JCenter, and not on Maven Central, so anyone using it will be affected.

What are your thoughts on publishing PhotoDraweeView on Maven Central or another channel?

**Comment by ongakuer** [comment]
99801cb385e73c1132c8f025b644eba10037fbeb
